/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_cliente_servidor.JFrame;

/**
 *
 * @author burgo
 */
public class MenuPrin extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrin
     */
    public MenuPrin() {
        initComponents();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jm_Opciones = new javax.swing.JMenu();
        Repuestis = new javax.swing.JMenu();
        JM_AgregarUnRepuesto = new javax.swing.JMenuItem();
        JM_EliminarRepuesto = new javax.swing.JMenuItem();
        JM_ListarRepuestos = new javax.swing.JMenuItem();
        JM_BuscarUnRepuesto = new javax.swing.JMenuItem();
        JM_CerrarSesion = new javax.swing.JMenuItem();
        InformacionContacto = new javax.swing.JMenu();
        Informacion = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBox1.setText("jCheckBox1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\burgo\\Desktop\\ProyectoProgra\\303990598_478735280926721_5967867203176425710_n.png")); // NOI18N

        jButton1.setText("jButton1");

        Jm_Opciones.setText("Opciones");

        Repuestis.setText("Repuestos");

        JM_AgregarUnRepuesto.setText("Agregar un Repuestos");
        JM_AgregarUnRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AgregarUnRepuestoActionPerformed(evt);
            }
        });
        Repuestis.add(JM_AgregarUnRepuesto);

        JM_EliminarRepuesto.setText("Eliminar un Repuesto");
        JM_EliminarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_EliminarRepuestoActionPerformed(evt);
            }
        });
        Repuestis.add(JM_EliminarRepuesto);

        JM_ListarRepuestos.setText("Lista de repuestos");
        JM_ListarRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ListarRepuestosActionPerformed(evt);
            }
        });
        Repuestis.add(JM_ListarRepuestos);

        JM_BuscarUnRepuesto.setText("Buscar un repuesto");
        JM_BuscarUnRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_BuscarUnRepuestoActionPerformed(evt);
            }
        });
        Repuestis.add(JM_BuscarUnRepuesto);

        Jm_Opciones.add(Repuestis);

        JM_CerrarSesion.setText("Cerrar Sesion");
        JM_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_CerrarSesionActionPerformed(evt);
            }
        });
        Jm_Opciones.add(JM_CerrarSesion);

        jMenuBar1.add(Jm_Opciones);

        InformacionContacto.setText("Mas de nosotros...");

        Informacion.setText("Informacion de contacto!");
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });
        InformacionContacto.add(Informacion);

        jMenuBar1.add(InformacionContacto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JM_AgregarUnRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AgregarUnRepuestoActionPerformed
        // TODO add your handling code here:
        AgregarUnRepuesto formulario = new AgregarUnRepuesto();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();

        
    }//GEN-LAST:event_JM_AgregarUnRepuestoActionPerformed

    private void JM_EliminarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_EliminarRepuestoActionPerformed
        // TODO add your handling code here:
         EliminarRepuesto formulario = new EliminarRepuesto();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();

    }//GEN-LAST:event_JM_EliminarRepuestoActionPerformed

    private void JM_BuscarUnRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_BuscarUnRepuestoActionPerformed
        // TODO add your handling code here:
         BuscarRepuesto formulario = new BuscarRepuesto();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();

    }//GEN-LAST:event_JM_BuscarUnRepuestoActionPerformed

    private void JM_ListarRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ListarRepuestosActionPerformed
        // TODO add your handling code here:
         ListRepuestos formulario = new ListRepuestos();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();

    }//GEN-LAST:event_JM_ListarRepuestosActionPerformed

    private void JM_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_CerrarSesionActionPerformed
        // TODO add your handling code here:
        InSec formulario = new InSec();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();

    }//GEN-LAST:event_JM_CerrarSesionActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        // TODO add your handling code here:
        InformacionContacto formulario = new InformacionContacto();
        
        formulario.setLocationRelativeTo(null);
        
        formulario.setVisible(true);
                
        this.dispose();
    }//GEN-LAST:event_InformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrin().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Informacion;
    private javax.swing.JMenu InformacionContacto;
    private javax.swing.JMenuItem JM_AgregarUnRepuesto;
    private javax.swing.JMenuItem JM_BuscarUnRepuesto;
    private javax.swing.JMenuItem JM_CerrarSesion;
    private javax.swing.JMenuItem JM_EliminarRepuesto;
    private javax.swing.JMenuItem JM_ListarRepuestos;
    private javax.swing.JMenu Jm_Opciones;
    private javax.swing.JMenu Repuestis;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
